version: '3.0'
services:
  ebkm1:
    container_name: ebkm1
    image: "ebkm:latest"
    ports:
      - "8080:8080"
    environment:
      ENV: DEV
    links:
      - logstash

  ebkm2:
    container_name: ebkm2
    image: "ebkm:latest"
    ports:
      - "8081:8080"
    environment:
      ENV: DEV
    links:
      - logstash

  nginx:
    container_name: nginx
    image: "nginx:test"
    ports:
      - "80:80"

  elasticsearch:
    build: elk/elasticsearch/
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - elk

  logstash:
    build: elk/logstash/
    container_name: logstash
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./elk/logstash/config:/etc/logstash/conf.d
    ports:
      - "9999:9999"
    links:
      - elasticsearch
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: elk/kibana/
    container_name: kibana
    volumes:
      - ./elk/kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge